### ISSUE TITLE
Call NotifyOfPropertyChange in a different thread?

### ISSUE THREAD

**Issue by gowthamnatarajan** [Caliburn-Micro/Caliburn.Micro#654] opened 2019-12-13 01:07 UTC
Is it possible to call `NotifyOfPropertyChange` from a different thread?

I have a `ViewModel` class with a method called `LoadData()` which calls `NotifyOfPropertyChange` for all variables in that class.

I also have a class which uses C#s Timer class to run a background method every 1 minute which fetches new data from DB. This method calls the `LoadData` method in the `ViewModel` class. But it does not refresh the UI. Should the `LoadData` method be called only from the UI thread?

Here are my classes:

```
public class ShellViewModel : Conductor<object>
{
    public List<MyClass> AllData {get; set;}
    
    public void LoadData()
    {
        NotifyOfPropertyChange(() => AllData);
    }
}
```

My Timer Class

```
public class RecurringTasks : PropertyChangedBase
{
    //This method runs in a background thread
    private void UpdateData()
    {
        //Code to connect to DB and get data
        _shellViewModel.AllData = //assign data from DB
        _shellViewModel.LoadData();
}
```
Whenever the Timer runs the UpdateData() method, I see that the data in the "AllData" field ShellViewModel actually gets updated. But the UI is not changing.

**Comment by nigel-sampson** [comment] 2019-12-13 01:30
The property changed notification in this sample would be fired on the UI thread. Given you observed behavior I don't seen any evidence that it's not.

Have you verified your binding is correct?

**Comment by gowthamnatarajan** [comment] 2019-12-13 01:36
`AllData` has the data. But the UI does not reflect the changes. The bindings are correct because, the data loads corrects when I call` LoadData()` in the constructor of the `ShellViewModel` class. But if I call `LoadData()` from a different thread, it is not working.

**Comment by nigel-sampson** [comment] 2019-12-13 01:44
How is it loading correct if you're calling LoadData before the data has loaded?

**Comment by gowthamnatarajan** [comment] 2019-12-13 01:48
I initially assign some data to `AllData` in the `OnViewLoaded` (not constructor) method and also call `LoadData`. That works and the UI shows data. So the binding should be correct. But if I call from the `RecurringTasks` in a separate thread then its not.

**Comment by nigel-sampson** [comment] 2019-12-13 02:30
You can force code onto the UI thread via the `Execute` class, does this fix the issue?

**Comment by gowthamnatarajan** [comment] 2019-12-13 02:37
What is the Execute class?

**Comment by nigel-sampson** [comment] 2019-12-13 03:05
`Caliburn.Micro.Execute`.

**Comment by gowthamnatarajan** [comment] 2019-12-14 10:11
Is there an example of how to write an Action? How do I create an Action which calls the LoadData method?

**Comment by nigel-sampson** [comment] 2019-12-16 01:28
``` csharp
Execute.OnUIThread(() => LoadData());
```

**Comment by gowthamnatarajan** [comment] 2019-12-16 02:07
Even if I do this, it is not working. The UI does not update itself. If I reload the page, then it updates itself because LoadData() is also being called in OnViewLoaded method.

**Comment by nigel-sampson** [comment] 2019-12-16 02:14
Seems like the issue isn't a UI thread related one but some other timing issue.

**Comment by gowthamnatarajan** [comment] 2019-12-16 02:18
This is the exact code:

```
private async void UpdateOptionsChain(object sender, EventArgs e)
{
    await _apiHelper.GetAllData(DateTime.Now.Date, RequestDateType.DateType.Max);
    Execute.OnUIThread(() => _container.GetInstance<ShellViewModel>().LoadData());
    Execute.OnUIThread(() => _container.GetInstance<SummaryViewModel>().LoadData());
    Execute.OnUIThread(() => _container.GetInstance<DetailsViewModel>().LoadData());
}
```
There are 3 viewModels which I am updating. GetAllData function updates all the data which are bound to the UI. I verified using breakpoints that the fields are indeed being updated.

Also, I created a button called "RefreshAll", which calls the LoadData() method for the 3 classes and that DOES update the UI.

**Comment by nigel-sampson** [comment] 2019-12-16 02:37
What are the lifetimes configured in your container for the view models? Typically view models are defined as being "per-request" so `_container.GetInstance<ShellViewModel>` will get a new view model that isn't the same one bound to the UI.

**Comment by gowthamnatarajan** [comment] 2019-12-16 02:44
I haven't configured any of that. Where and how should I do that?

**Comment by nigel-sampson** [comment] 2019-12-16 02:47
It will be in the configuration of your container at application startup. Something like
``` csharp
_container.PerRequest<ShellViewModel>();
```
If this is your problem you'll need to update your `UpdateData` method to `LoadData` on the same view model instance.

**Comment by mvermef** [comment] 2019-12-16 02:48
He's probably not keeping the viewmodel it's getting destroyed after each use

**Comment by gowthamnatarajan** [comment] 2019-12-16 02:50
Instead of using PerRequest, how do I make sure there is only 1 instance of the the class during the entire lifetime?Something like:

`_container.Singleton<ShellViewModel>();`

would work?

**Comment by nigel-sampson** [comment] 2019-12-16 02:51
That would work but could have side effects in other areas of your application.

I'm going to close this issue out as it's definitely not a framework bug.

**Closed by nigel-sampson** 2019-12-16 02:51 UTC

**Comment by gowthamnatarajan** [comment] 2019-12-16 02:58
Thanks. Making all ViewModels Singleton's worked and there were no other issues in the application. Its because, I always though all ViewModels would be singleton by default and wrote code accordingly.
