### ISSUE TITLE
ContentView's Model is ignored in Xamarin.Forms

### ISSUE THREAD

**Issue by nologinatgit** [Caliburn-Micro/Caliburn.Micro#349] opened 2016-07-21 07:20 UTC
I have the following XAML for a parent view:

``` xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentPage x:Class="MyProject.Views.MainContainerView"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:cm="clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms"
             Title="Container">
    <ContentView cm:View.Model="{Binding DetailViewModel}" />
</ContentPage>
```

This is its ViewModel:

``` csharp
public class MainContainerViewModel : Screen
{
    public MainContainerViewModel()
    {
      DetailViewModel = new DetailsViewModel ();
    }

    public DetailsViewModel DetailViewModel{ get; set; }

    public void Save()
    {
      var y = 7;
    }
}
```

This is the DetailsView:

``` xaml
<?xml version="1.0" encoding="utf-8" ?>
<ContentView x:Class="MyProject.Views.DetailsView"
             xmlns="http://xamarin.com/schemas/2014/forms"
             xmlns:x="http://schemas.microsoft.com/winfx/2009/xaml"
             xmlns:cm="clr-namespace:Caliburn.Micro.Xamarin.Forms;assembly=Caliburn.Micro.Platform.Xamarin.Forms"
             xmlns:sys="clr-namespace:System;assembly=mscorlib">
    <Button cm:Message.Attach="Save" Text="Save" />
</ContentView>

```

This is the ViewModel for the Details:

``` csharp
public class DetailsViewModel : Screen
{
   public void Save()
    {
      var y = 2;
    }
}
```

I always end up in the MainContainerViewModel's `Save` method instead of the detail viewmodel.

Why? What should I modify?

**Comment by nigel-sampson** [comment] 2016-07-21 09:21
This looks like a bug. I'm not sure about a work around at the moment.

**Comment by nigel-sampson** [comment] 2016-11-03 10:04
This looks to be a timing issue caused by lack of decent events in Xamarin.Forms. When we "bind" the view and view model together we set an attached dependency property on the view called `Action.Target`.

When the element with the message attached is `Loaded` into the visual tree we walk up the tree we find the `Target` and therefore which view model to call the method on (the bubbling works by continuing the traversal if the target doesn't have the method).

In this case Xamarin Forms doesn't have an equivalent of `Loaded` so I've been hacky and used `BindingContextChanged`. What's happened is this event is firing before the target could be set on the details view and therefore it finds the container.

Switching some order of operations (bind the view / view model before adding to visual tree) lets us set the target before causing the event to fire.

It's something I've wanted to do in the main framework for a while now, but could be a breaking change. Happy to try it out in Xamarin.Forms first.

**Comment by nigel-sampson** [comment] 2016-11-03 10:10
Just pushed a fix, if you want to have a look and see if it resolves in your app as well.

**Closed** 2016-12-06 09:28 UTC
Labels: bug
