### ISSUE TITLE
How to have design time support for nested view models in Caliburn Micro?

### ISSUE THREAD

**Issue by stajs** [Caliburn-Micro/Caliburn.Micro#214] opened 2015-08-19 00:31 UTC
I previously asked this question on SO, and a commenter suggested I ask here. Original SO: 

http://stackoverflow.com/questions/29795367/how-to-have-design-time-support-for-nested-view-models-in-caliburn-micro

---

Using VS2013 and Caliburn.Micro 2.0.2

Given this example of: 
1. a shell view model that has a nested view model property, and
2. both the shell and nested view models having a `Name` property:

![Project](http://i.stack.imgur.com/BMbZi.png)

It seems that during design time the nested view model property is ignored. Is there a way to support this?

``` csharp
public class NestedViewModel : PropertyChangedBase
{
    private string _name;

    public string Name
    {
        get { return _name; }
        set
        {
            _name = value;
            NotifyOfPropertyChange(() => Name);
        }
    }

    public NestedViewModel()
    {
        Name = "Nested";
    }
}
```

&nbsp;

``` xml
<UserControl
    x:Class="WpfApplication1.Views.NestedView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006" 
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:cal="http://www.caliburnproject.org"
    xmlns:viewModels="clr-namespace:WpfApplication1.ViewModels"
    mc:Ignorable="d"
    d:DataContext="{d:DesignInstance Type=viewModels:NestedViewModel, IsDesignTimeCreatable=True}"
    cal:Bind.AtDesignTime="True">
    <Grid>
        <Label x:Name="Name" FontSize="16" Background="LightGreen"/>
    </Grid>
</UserControl>
```

The green label shows the correct `Name` for the nested view model in the designer:

![Nested](http://i.stack.imgur.com/5Qkm2.png)

``` csharp
public class ShellViewModel : PropertyChangedBase
{
    private string _name;
    private NestedViewModel _nestedViewModel;

    public string Name
    {
        get { return _name; }
        set
        {
            _name = value;
            NotifyOfPropertyChange(() => Name);
        }
    }

    public NestedViewModel NestedViewModel
    {
        get { return _nestedViewModel; }
        set
        {
            if (Equals(value, _nestedViewModel)) return;
            _nestedViewModel = value;
            NotifyOfPropertyChange(() => NestedViewModel);
        }
    }

    public ShellViewModel()
    {
        NestedViewModel = new NestedViewModel();
        Name = "Shell";
    }
}
```

&nbsp;

``` xml
<UserControl
    x:Class="WpfApplication1.Views.ShellView"
    xmlns="http://schemas.microsoft.com/winfx/2006/xaml/presentation"
    xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
    xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
    xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
    xmlns:viewModels="clr-namespace:WpfApplication1.ViewModels"
    xmlns:cal="http://www.caliburnproject.org"
    mc:Ignorable="d"
    d:DataContext="{d:DesignInstance Type=viewModels:ShellViewModel, IsDesignTimeCreatable=True}"
    cal:Bind.AtDesignTime="True">
    <Grid>
        <Grid.RowDefinitions>
            <RowDefinition/>
            <RowDefinition/>
        </Grid.RowDefinitions>
        <ContentControl Grid.Row="0" x:Name="NestedViewModel"/>
        <Label Grid.Row="1" x:Name="Name" FontSize="16" Background="RoyalBlue"/>
    </Grid>
</UserControl>
```

The green label should show the nested view model `Name` property in the designer, but instead shows the value of the shell view model:

![Shell](http://i.stack.imgur.com/TDsKB.png)

It does bind correctly at runtime:

![Run time](http://i.stack.imgur.com/0Rk2H.png)

[Example](https://github.com/stajs/WpfApplication1)

**Comment by nigel-sampson** [comment] 2015-08-19 00:38
Thanks for the bug report.

**Comment by stajs** [comment] 2015-08-19 00:48
No problem.

I should add a note from the commentary too: when ShellViewModel and NestedViewModel have different property names, you will only see the blue label (ShellViewModel).

**Comment by tibel** [comment] 2015-10-02 15:43
In VS2015 the same sample shows following in the designer.

NestedView:
![nestedview_vs2015](https://cloud.githubusercontent.com/assets/387395/10250727/e8768666-692c-11e5-93a1-f93d5b8603ba.PNG)

ShellView:
![shellview_vs2015](https://cloud.githubusercontent.com/assets/387395/10250722/e07e6f46-692c-11e5-8fce-547225223646.PNG)

Seems that the VS2015 designer behaves different.
My impression is that the bootstrapper code is not executed.

**Comment by quetzalcoatl** [comment] 2016-07-04 14:58
I got both of above-mentioned behaviors in current 3.0.1 version.
I upgraded a project that was using 2.x on VS2012/3 version to 3.0.1 on VS2015, and at first I got the 'empty box' behavior - and indeed the bootstrapper code was not ran.

In my app I had the `bootstrapper.Initialize()` pulled out of bootstrapper's constructor and called it manually*) in app.xaml.cs, so in RunTime it worked fine and I'm pretty sure it also half-magically worked on DesignTime. But in VS2015 with 3.0.1 it started to work in RunTime only and in DesignTime it displayed only empty boxes instead of subviews.

When I moved 'Initialize()' back to bootstrapper's constructor and did a clean&rebuild, it presented "cannot find view for xxViewModel". It began to work after restarting visual studio, and now it I get the behavior from the first post - designtime bindings seem to pull data from outer context, not from the nested context.
 
*) small hack to prevent hard-to-read XamlParseExceptions (which also sometimes caused VS2012 to crash) and to try-catch any exceptions thrown during container setup and show a nice messagebox to the user (instead of insta-crash).

**Comment by nugarin** [comment] 2016-07-14 13:26
Hello. 

I can confirm that this issue is present in the VS2015 with Caliburn.Micro 3.0.1

I am following a viewmodel-first pattern, with "Design" subclasses for viewmodels.


Example:

   ```
        public MainViewModel(IEventAggregator eventAggregator, ILogger log, ApplicationEventsViewModel applicationEventsViewModel) : base(eventAggregator)
        {
            ApplicationEventsViewModel = applicationEventsViewModel;
            _log = log;
            _log?.Info("Initialised");
        }

        public class Design:MainViewModel
        {
            private string _testBinding;
            private string _designTest;

            public Design():base(null, null, new ApplicationEventsViewModel(null))
            {
                DesignTest = "I am in main";

                ApplicationEventsViewModel.ApplicationEvents.Add(new ApplicationEvent()
                {
                    Message = "why no work??"
                });

            }

    ....

     public class Design : ApplicationEventsViewModel
        {
            private string _designTest;

            public string DesignTest
            {
                get { return _designTest; }
                set
                {
                    if (value == _designTest) return;
                    _designTest = value;
                    NotifyOfPropertyChange(() => DesignTest);
                }
            }

            public Design() : base(null)
            {
                DesignTest = "werk dammit!";

                ApplicationEvents.Insert(0, new ApplicationEvent
                {
                    EventTime = DateTime.Now.AddMinutes(-1),
                    Message = "<First Message>"
                });

```

Given viewmodels "MainViewModel" and it's nested viewmodel "ApplicationEventsViewModel".
Both work correctly in the design time view with their own properties.
However, bindings in the nested view try to bind to the main view model.

Textblock with name "DesignTest" will show "werk dammit", and the events from the ApplicationEvents collection when I open ApplicationEventsView
ApplicationEventsView that is hosted in a contentcontrol inside MainView, shows "I am in main" and no events.

**Comment by nugarin** [comment] 2016-07-14 13:32
I am also using a custom ViewModelLocator to allow thse subclasses, but I doubt this is causing the problem..

```

    protected override void StartDesignTime()
        {
            LogManager.GetLog = type => new NullLogger();

            var storedLocator = ViewLocator.LocateForModelType;

            ViewLocator.LocateForModelType = (type, o, arg3) =>
            {
            //    Debugger.Break();
                var res = type != null && type.Name.EndsWith("Design")
                    ? storedLocator(type.BaseType, o, arg3)
                    : storedLocator(type, o, arg3);

                return res;
            };

            base.StartDesignTime();
        }

cal:Bind.AtDesignTime="True"
        d:DataContext="{d:DesignInstance Type=viewModels:MainViewModel+Design, IsDesignTimeCreatable=True}"

...
d:DataContext="{d:DesignInstance Type=viewModels:ApplicationEventsViewModel+Design, IsDesignTimeCreatable=True}"
             cal:Bind.AtDesignTime="True"


```

**Comment by beachwalker** [comment] 2016-10-14 05:04
Is this somewhere in the schedule?

**Comment by nigel-sampson** [comment] 2016-10-14 08:28
I've been having trouble recreating a lot of these issues, different behaviors on different versions of the designers don't help either.

Getting rather sick of their flaky behavior.

**Comment by eogas** [comment] 2016-10-14 13:30
@nigel-sampson When you have time, can you try to reproduce this issue with the reproducer case I've created here: https://github.com/eogas/CaliburnMicroDesignTimeNestedBindingBug

I tried to boil it down to the simplest possible example, and I've been able to reproduce it consistently on multiple machines with VS2015 Update 3.  I hadn't considered that there is different behavior in different VS versions.  I should be able to test it on VS2012 later today.

**Comment by superware** [comment] 2016-11-08 00:29
@eogas say, have you tested this on VS2012? thanks.

**Comment by nigel-sampson** [comment] 2016-11-09 08:25
I've pushed a fix that resolves this in VS2013, would appreciate some testing in VS2012 if anyone can help out.

**Comment by eogas** [comment] 2016-11-09 14:41
@superware @nigel-sampson Sorry for the delay, I just tested out my reproducer against this change on VS2012 Professional with Update 4 and it appears to fix the issue as intended.

**Comment by nigel-sampson** [comment] 2016-11-09 20:29
Thanks for the help. Glad to hear it's resolved in VS 2012.

**Closed** 2016-12-06 09:28 UTC
Labels: bug

**Comment by nietras** [comment] 2022-04-08 10:37
@KasperSK I am having similar issues as mentioned in this issue but in VS2022 using Caliburn.Micro 3.2.0, is this a known issue still or for 2022? Also see #379 
Note still using version 3 and cannot easily upgrade to that.

**Comment by vb2ae** [comment] 2022-04-08 11:09
@nietras What version of .net framework are you using?

**Comment by KasperSK** [comment] 2022-04-08 11:23
@nietras This is the first I am hearing of it. Can it be reproduced with the sample project in this issue?

**Comment by nietras** [comment] 2022-04-08 18:20
@vb2ae hmm mail reply appears to not have come here. .NET 6 actually. Note that at runtime things work fine.

@KasperSK cloned https://github.com/eogas/CaliburnMicroDesignTimeNestedBindingBug and yes it appears the issue can be reproduced with the sample project as shown below nothing is shown in designer.

![image](https://user-images.githubusercontent.com/10798831/162499251-65918823-7241-4097-a53e-d404bd8bad2d.png)

While at runtime they are.

![image](https://user-images.githubusercontent.com/10798831/162499379-0496f277-ce3d-4953-9061-ebd51f00447f.png)

**Comment by nietras** [comment] 2022-04-08 18:25
This is the same after updating to 3.2.0. Git repo was 3.0.1

**Comment by vb2ae** [comment] 2022-04-10 21:16
@nietras Visual Studio 2022 has hot reload so you can change the xaml while the app is running and the window should show the changes.  I do not think they put as much design time data support in VS 2022 as in previous versions

**Comment by nietras** [comment] 2022-04-19 12:11
@vb2ae hot reload is definitely nice but for our work not really great. Is there any chance this might be fixable for 3? How can you debug what goes wrong? I would think it relates to view locator.

**Comment by nietras** [comment] 2022-04-20 09:22
Another thing that appears broken is the "automatic binding" based on name of ui element e.g.:
```xaml
<TextBox x:Name="Directory" />
```
will automatically bind to a property named `Directory` at runtime, but at design-time it no longer does, but if you write:
```xaml
<TextBox Text="{Binding Directory}"/>
```
it does. We have used this convention a lot so would have to change a lot of code to fix it. So hoping this could be fixed too.

**Comment by nietras** [comment] 2022-04-20 10:43
@vb2ae thanks, looks like `namedElements` is always empty/0 count when running in designer. I basically just override BindActions/BindProperties in a `ModuleInitializer` to trace what happens when designer runs.

At runtime the expected `namedElements` exist.

```csharp
        var oldBindActions = ViewModelBinder.BindActions;
        ViewModelBinder.BindActions = (IEnumerable<FrameworkElement> namedElements, Type viewModelType) =>
        {
            Trace.WriteLine($"{nameof(ViewModelBinder.BindActions)} look in " +
                $"{namedElements.Count()}:{string.Join(",", namedElements.Select(e => e.Name))} for {viewModelType.Name}");
             ...
 
        var oldBindProperties = ViewModelBinder.BindProperties;
        ViewModelBinder.BindProperties = (IEnumerable<FrameworkElement> namedElements, Type viewModelType) =>
        {
            Trace.WriteLine($"{nameof(ViewModelBinder.BindProperties)} look in " +
                $"{namedElements.Count()}:{string.Join(",", namedElements.Select(e => e.Name))} for {viewModelType.Name}");
            ....
```

**Comment by nietras** [comment] 2022-04-20 10:50
Could this be related to:

https://github.com/Caliburn-Micro/Caliburn.Micro/blob/7ef1a9a2820a45b3bffc41a5d6f5b04ef661988b/src/Caliburn.Micro.Platform/ViewModelBinder.cs#L250-L254

or how `GetNamedElements` is defined:

https://github.com/Caliburn-Micro/Caliburn.Micro/blob/7ef1a9a2820a45b3bffc41a5d6f5b04ef661988b/src/Caliburn.Micro.Platform/BindingScope.cs#L124-L126

I kind see why there would be any differences from design-time from at runtime here, though.

**Comment by nietras** [comment] 2022-04-21 11:51
Looking at callstack when designer runs and calls `GetFirstNonGeneratedView` is appears the designer instantiates a "naked" `UserControl` and not the actual `class` for the view. This appears to cause `GetNamedElements` to fail since it will look at `UserControl` and not a specific view type. What I don't understand is why the specific view type is not used but `UserControl`?

At runtime this would then be `LogView` or something instead. It also appears the ctor for `LogView` is not called which it used to in the past I believe, different designer perhaps.
```
[21068] GetFirstNonGeneratedView found UserControl for UserControl 
[21068]    at Caliburn.Micro.ViewModelBinder.<>c.<.cctor>b__10_3(Object viewModel, DependencyObject view, Object context) 
DependencyObject view, Object context) 
[21068]    at Caliburn.Micro.Bind.DataContextChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) 
[21068]    at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e) 
[21068]    at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e) 
[21068]    at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args) 
[21068]    at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType) 
[21068]    at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal) 
[21068]    at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value) 
[21068]    at System.Windows.Data.BindingOperations.SetBinding(DependencyObject target, DependencyProperty dp, BindingBase binding) 
[21068]    at Caliburn.Micro.Bind.AtDesignTimeChanged(DependencyObject d, DependencyPropertyChangedEventArgs e) 
[21068]    at System.Windows.DependencyObject.OnPropertyChanged(DependencyPropertyChangedEventArgs e) 
[21068]    at System.Windows.FrameworkElement.OnPropertyChanged(DependencyPropertyChangedEventArgs e) 
[21068]    at System.Windows.DependencyObject.NotifyPropertyChange(DependencyPropertyChangedEventArgs args) 
[21068]    at System.Windows.DependencyObject.UpdateEffectiveValue(EntryIndex entryIndex, DependencyProperty dp, PropertyMetadata metadata, EffectiveValueEntry oldEntry, EffectiveValueEntry& newEntry, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType) 
[21068]    at System.Windows.DependencyObject.SetValueCommon(DependencyProperty dp, Object value, PropertyMetadata metadata, Boolean coerceWithDeferredReference, Boolean coerceWithCurrentValue, OperationType operationType, Boolean isInternal) 
[21068]    at System.Windows.DependencyObject.SetValue(DependencyProperty dp, Object value) 
[21068]    at System.Windows.Baml2006.WpfMemberInvoker.SetValue(Object instance, Object value) 
[21068]    at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(XamlMember member, Object obj, Object value) 
[21068]    at MS.Internal.Xaml.Runtime.ClrObjectRuntime.SetValue(Object inst, XamlMember property, Object value) 
[21068]    at System.Xaml.XamlObjectWriter.SetValue(Object inst, XamlMember property, Object value) 
[21068]    at System.Xaml.XamlObjectWriter.Logic_ApplyPropertyValue(ObjectWriterContext ctx, XamlMember prop, Object value, Boolean onParent) 
[21068]    at System.Xaml.XamlObjectWriter.Logic_DoAssignmentToParentProperty(ObjectWriterContext ctx) 
[21068]    at System.Xaml.XamlObjectWriter.WriteEndMember() 
[21068]    at System.Xaml.XamlWriter.WriteNode(XamlReader reader) 
[21068]    at System.Windows.Markup.WpfXamlLoader.TransformNodes(XamlReader xamlReader, XamlObjectWriter xamlWriter, Boolean onlyLoadOneNode, Boolean skipJournaledProperties, Boolean shouldPassLineNumberInfo, IXamlLineInfo xamlLineInfo, IXamlLineInfoConsumer xamlLineInfoConsumer, XamlContextStack`1 stack, IStyleConnector styleConnector) 
[21068]    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, IXamlObjectWriterFactory writerFactory, Boolean skipJournaledProperties, Object rootObject, XamlObjectWriterSettings settings, Uri baseUri) 
[21068]    at System.Windows.Markup.WpfXamlLoader.Load(XamlReader xamlReader, Boolean skipJournaledProperties, Uri baseUri) 
[21068]    at System.Windows.Markup.XamlReader.Load(XamlReader xamlReader, ParserContext parserContext) 
[21068]    at System.Windows.Markup.XamlReader.Load(XmlReader reader, ParserContext parserContext,
[21068]  XamlParseMode parseMode, Boolean useRestrictiveXamlReader, List`1 safeTypes) 
[21068]    at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext, Boolean useRestrictiveXamlReader) 
[21068]    at System.Windows.Markup.XamlReader.Load(Stream stream, ParserContext parserContext) 
[21068]    at Microsoft.VisualStudio.XSurface.Wpf.Tap.SurfaceService.LoadXamlContentInternal(TapDocument document) 
[21068]    at Microsoft.VisualStudio.XSurface.Wpf.Tap.SurfaceService.BuildDocument(TapDocument document) 
[21068]    at Microsoft.VisualStudio.XSurface.Wpf.Tap.SurfaceService.HandleCreateSurfaceInternal(CreateSurfaceRequestInfo requestInfo) 
[21068]    at Microsoft.VisualStudio.XSurface.Wpf.Tap.SurfaceService.<>c__DisplayClass28_0.<HandleCreateSurface>b__0() 
[21068]    at System.Windows.Threading.DispatcherOperation`1.InvokeDelegateCore() 
[21068]    at System.Windows.Threading.DispatcherOperation.InvokeImpl() 
[21068]    at System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(Object state) 
[21068]    at MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj) 
[21068]    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state) 
[21068]    at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state) 
[21068]    at MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state) 
[21068]    at System.Windows.Threading.DispatcherOperation.Invoke() 
[21068]    at System.Windows.Threading.Dispatcher.ProcessQueue() 
[21068]    at System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) 
[21068]    at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled) 
[21068]    at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o) 
[21068]    at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs) 
[21068]    at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler) 
[21068]    at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs) 
[21068]    at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam) 
[21068]    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg) 
[21068]    at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg) 
[21068]    at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame) 
[21068]    at System.Windows.Threading.Dispatcher.PushFrame(DispatcherFrame frame) 
[21068]    at System.Windows.Threading.Dispatcher.Run() 
[21068]    at System.Windows.Application.RunDispatcher(Object ignore) 
[21068]    at System.Windows.Application.RunInternal(Window window) 
[21068]    at System.Windows.Application.Run() 
[21068]    at Microsoft.VisualStudio.XSurface.Wpf.WpfSurfaceApp.Main(String[] args) 
```

**Comment by vb2ae** [comment] 2022-04-25 11:01
created a new issue #804  for this

**Comment by nietras** [comment] 2022-10-11 07:47
.NET 6 actually. Note everything works fine at runtime same as this issue.
