### ISSUE TITLE
Update Samples to use new assemblies

### ISSUE THREAD

**Issue by nigel-sampson** [Caliburn-Micro/Caliburn.Micro#450] opened 2017-06-10 04:08 UTC
- [x] Remove unsupported samples platforms
- [x] Have samples reference new projects output
- [ ] Add UWP Xamarin.Forms Setup Sample
- [ ] Add UWP Xamarin.Forms Features Sample
- [ ] Remove unsupported platforms from Setup samples
- [ ] Shift to .NET Standard Xamarin.Forms samples

**Comment by godrose** [comment] 2017-06-16 04:54
Hi.
Thanks for the great effort.
Can you please elaborate on features to be included into or rendered obsolete from 4.0.0?
What is the planned release date?
Thanks in advance @nigel-sampson

**Comment by nigel-sampson** [comment] 2017-06-16 09:27
There shouldn't be any major features being made obsolete in `4.0.0`.

Some older platforms (.NET 4.0, Silverlight, Windows Phone etc) will be dropped, but the `3.*.*` releases will continue to work for them.

There'll probably be a LOT of breaking changes though, moving to an async model for lifeycle and navigation will cause changes through out your view model.

**Comment by godrose** [comment] 2017-06-16 09:33
I see. I'm already using an async version of navigation service so that is OK.
What is the planned date then?
Also are you planning to support PCL or drop it as well? If yes what's the version of .NETStandard? Thanks.

**Comment by nigel-sampson** [comment] 2017-06-16 11:27
Not sure I'm time frames, lots to be done.

`Caliburn.Micro.Core` can target .NET Standard 1.0 so lots of support there. `Caliburn.Micro.Xamarin.Forms` will be 1.6.

**Comment by godrose** [comment] 2017-06-16 11:47
Cool. Thanks. Will check if I have spare time to help with the effort. @nigel-sampson

**Comment by rossvegas** [comment] 2017-06-26 08:21
Hi @nigel-sampson I am really looking forward to V4 as well, I would love to help out, docs, reviews anything.

**Comment by nigel-sampson** [comment] 2017-06-27 00:06
Thanks, right now the .NET Standard and Multi Targeting changes to the solution have been WOMM'd (Works on My Machine). I'd love some checks from other people that they can do a clone and a clean build using VS 2017 / Xamarin and the samples work correctly.

**Comment by nigel-sampson** [comment] 2017-06-27 00:07
Also the two UWP samples in the checklist on this issue would be easy ways to jump into open source.

**Comment by rossvegas** [comment] 2017-06-27 11:25
So I have done neat clone and tried to open the src solution on two machines with VS2017 with .net core and Xamarin. Nuget fails to load the Caliburn.Micro.Core Project in the package manager output window I get the following error 

"Error occurred while restoring NuGet packages: The operation failed as details for project Caliburn.Micro.Platform could not be loaded." 

Because nuget cant load System.Runtime.Serialization.Primitives nothing will build and its error city.

I can open a command prompt and do a dotnet restore and it restores successfully. Opening in visual studio I can then build and its all good.

I have done a bunch of googling tonight and was unable to find anything that could be causing it. There seems to have been a bug that was fixed in nuget a few months back but I have the latest fully patched VS 2017 with package manager 4.2.0.2457 so I don't think that is the problem.

I am going to spin up an azure vm with visual studio and see if that gives the same issues.

**Comment by rossvegas** [comment] 2017-06-27 12:04
So brand new Azure VM with VS2017 exibits the same behavior with the error while restoring nuget packages. I could give you a login @nigel-sampson if you wanted to have a look yourself.

**Comment by nigel-sampson** [comment] 2017-06-28 02:04
That's certainly a surprising place to fail, I'll try and look into it a bit to see what's causing the problem. Do suspect it's a nuget issue, do other projects restore correctly? What about other projects referencing the same package.

**Comment by rossvegas** [comment] 2017-06-28 03:46
I have confirmed that after restoring and building the core project the problem then occurs at the platform project which is also .NET Standard. The test project which is .NET 4.5 restores packages and builds just fine. After doing a dotnet restore at the sln level a dotnet build for the whole solution works just fine.

**Comment by rossvegas** [comment] 2017-06-28 08:27
I have tested the samples folder. Features and setup load and build just fine. 

Scenarios specifically the functional project is the only area in which I am having trouble. I have F# installed but I only have VS 2017 installed on this machine. I am getting the error

`Error	FS0193	The module/namespace 'System.Net' from compilation unit 'System' did not contain the namespace, module or type 'WebClient'	Scenario.Functional.Core`	
 
Opening ShellViewModel.fs and AssemblyInfo.fs I get a red squiggle under the n in namespace. Mousing over gives the for mentioned error in a tool-tip

**Comment by nigel-sampson** [comment] 2017-06-28 21:17
Thanks for the information, curious why there there isn't a `dotnet restore` on first build.

**Comment by nigel-sampson** [comment] 2017-06-29 03:59
Looks like this is a known issue Nuget/Home#5226 with a work around.

**Comment by rossvegas** [comment] 2017-06-29 06:12
I actually came across that solution and added 
`<PackageId>$(MSBuildProjectName)</PackageId>`
to the core project only a couple of days ago. However it still gave the same error i mentioned previously so I thought it was something else.

I just went back and added it to all three .net standard projects and now it restores perfectly. 

Should I do a pull request for the changes? (as trivial as they are)

**Comment by nigel-sampson** [comment] 2017-06-29 21:10
Happy to take a pull request for this, bit swamped with life at the moment.

**Comment by rossvegas** [comment] 2017-07-11 11:28
Hey @nigel-sampson I have added a Xamarin UWP setup sample and removed the old silverlight projects, I used code snippets from your NDC talks and the existing UWP app but cant quite make it go. You can take a look here

https://github.com/rossvegas/Caliburn.Micro/tree/dev/4.0.0/samples/setup

It compiles and runs but fails to load the HomeView. I think if you had a look at it it wouldn't take you long to figure out what I have missed.

**Comment by nigel-sampson** [comment] 2017-07-19 10:11
Sorry, been head down working on the code for the next NDC talk. I'll take a look at this soon.

**Comment by rossvegas** [comment] 2017-08-28 00:05
Hey @nigel-sampson If you have a little time, could you have a look at my branch

https://github.com/rossvegas/Caliburn.Micro/tree/dev/4.0.0/samples/setup and see what I might have missed.

Thanks

**Comment by nigel-sampson** [comment] 2017-09-06 01:42
Sorry @rossvegas, it's on my list for the next few days

**Comment by nigel-sampson** [comment] 2017-09-25 09:06
@rossvegas a lot of the structure looks good, the only thing that appears to be missing is the host native view. If you look at the [NDC sample](https://github.com/nigel-sampson/talks/tree/master/ndc-sydney-2016/NDC.Build.Forms.App.UWP) it contains a `HostView` that's reference in `[OnLaunched](https://github.com/nigel-sampson/talks/blob/master/ndc-sydney-2016/NDC.Build.Forms.App.UWP/App.xaml.cs#L33)`.

That should be pretty much it.

**Comment by rossvegas** [comment] 2017-09-27 08:17
Hi @nigel-sampson I had a fair few issues with dependencies trying to make minimal modifications to the existing UWP and Xamarin forms projects, so I have re created the projects using VS2017 and applied the changes. It is all working really well. Please have a look and let me know what I can do next.

**Comment by bryanbcook** [comment] 2018-09-20 21:55
Was there a pull-request for this? The default template for Xamarin.Forms 3.x use .NET Standard instead of PCL. I was able to move the PCL over to .NET Standard and latest Xamarin.Forms bits fairly easily. 

I'm assuming I'd fork the @rossvegas repository and then issue you a PR. Then we need to get a PR back to the origin?

**Closed** 2018-12-27 09:53 UTC
Labels: help wanted
