### ISSUE TITLE
Message.Attach attaches a handler multiple time to the same UI element

### ISSUE THREAD

**Issue by mruf** [Caliburn-Micro/Caliburn.Micro#289] opened 2016-01-29 08:39 UTC
We use the attached property Message.Attach extensively to attach event handlers in our viewmodels to UI element events such as Click, Tap etc. This has worked fine in our Windows 10 UWP app so far.
After upgrading from Caliburn beta1 to beta2 however we noticed some strange behavior:
The event handlers are now attached to the UI element's event multiple times, even if the UI element is not recreated. This means that they are executed multiple times for a single Click, Tap etc

To reproduce:
On the main screen of the app create a button and attach a handler from the viewmodel to the button's click event like this:

<Button x:Name="TestButton"
        Content="Test"
        cal:Message.Attach="[Event Click] = [Action TestHandler()]"/>

Click the button. TestHandler() will be executed once, just as expected.
Navigate away from the screen to another screen of the app by using the navigation service. 
Press the Back button to return to the main screen.
Click the button. TestHandler() will be executed twice.

Every time you navigate away and come back to the screen by pressing the back button the handler will be reattached even though it has already been attached once.

While updating from beta1 to beta2 we also had to add the package Microsoft.Xaml.Behaviors.Uwp.Managed. I don't know if this has any relevance to the issue however.
We are using Windows 10 Build 10586 as target.

**Comment by gruan01** [comment] 2016-01-29 18:17
I have the same question,
Because Page's NavigationCacheMode set as Required or Enable.
IF not set it, all work fine.

**Comment by nigel-sampson** [comment] 2016-02-01 23:03
Yup, the problem is a bug in the Microsoft/XamlBehaviors#55 SDK where the event trigger doesn't detach from the event correctly. It's fixed in source so building a local copy will work.

I believe a 1.0.4 release with this fix should be out soon.

**Closed by nigel-sampson** 2016-02-01 23:03 UTC

**Comment by gruan01** [comment] 2016-02-02 01:52
Thanks very much.
