### ISSUE TITLE
Message.Attach not passing parameters by name

### ISSUE THREAD

**Issue by jonferreira** [Caliburn-Micro/Caliburn.Micro#168] opened 2015-05-06 11:12 UTC
```XAML
<TextBox x:Name="TemplateEmail" Grid.Row="1" Margin="0,5,0,0" IsEnabled="{Binding ElementName=EnviaEmail, Path=IsChecked}">
    <TextBox.ContextMenu>
        <ContextMenu>
            <MenuItem Header="Cliente" cal:Message.Attach="[Click] = [Action ContextMenuCliente(TemplateEmail.Name, TemplateEmail.CaretIndex)]"  />
            <MenuItem Header="Contacto" cal:Message.Attach="[Click] = [Action ContextMenuContacto($source)]"  />
        </ContextMenu>
    </TextBox.ContextMenu>
</TextBox>```

Greetings,

I'm using the code above to "mimic" Copy + Paste in MMV: i know the ViewModel property name (TemplateEmail.Name, know where the cursor is TemplateEmail.CaretIndex so i can now "paste" my text in the correct place.

However for some reason i'm simple getting null and 0 instead of the correct values. variables such as $view, $this, etc are working so it seems to be related to named FrameworkElements?

I know i can't pass a FrameworkElement as a parameter with Message.Attach but i assumed i could at least pass some specific properties?

**Comment by nigel-sampson** [comment] 2015-05-06 19:54
The Caliburn.Micro parser isn't that smart, it wasn't really designed to fully parse out properties.if you use just `TemplateEmail` rather than `TemplateEmail.Name` it will return you the `Text` property (specified by the convention).

There's a couple of ways to solve this, you could use `$this` to get the `TextBox` as parameter, isn't very MVVM though,

Another solution is to create your own [Custom Special Values](http://compiledexperience.com/blog/posts/special-values/) for same $name and $caretIndex and which point you can do anything you like.

**Comment by jonferreira** [comment] 2015-05-07 09:00
Hi Nigel,
Thanks for replying.
$this won't work, unfortunately since it will return the MenuItem instead. A Custom Special Value won't work either because it was not the TextBox that triggered the event . ofc there''s ways around this but since i'm planing on having this kind of situation across my App id say they are not reliable.
As an alternative i guess i can pass $this to the ModelView (soooo ugly) and do something like "$this.parent.parent" or whatever is needed to reach the TextBox.
Another option is to pass the TextBox as a parameter of a function during page Load
```xaml
<i:Interaction.Triggers>
                                <i:EventTrigger EventName="Loaded">
                                    <cal:ActionMessage MethodName="setTPL">
                                        <cal:Parameter Value="{Binding ElementName=TPL}" />
                                    </cal:ActionMessage>
                                </i:EventTrigger>
                            </i:Interaction.Triggers>
```
Again terrible ugly and definitely not MVVM
All i wanted to do is to have a "true" MVVM Copy+Paste - no more ideas?

**Comment by nigel-sampson** [comment] 2015-05-07 21:07
You potentially could still use a custom special value with some extra work. The `ActionExecutionContext.Source` will be the `MenuItem` where you can `Parent.Parent` has a self contained hack.

Thinking about it though the better way may be to use the full syntax.

``` xml
<TextBox x:Name="TemplateEmail">
    <TextBox.ContextMenu>
        <ContextMenu>
            <MenuItem Header="Cliente">
                <i:EventTrigger EventName="Click">
                    <cal:ActionMessage MethodName="ContextMenuCliente">
                        <cal:Parameter Value="{Binding Name, ElementName=TemplateEmail}" />
                        <cal:Parameter Value="{Binding CaretIndex, ElementName=TemplateEmail}" />
                    </cal:ActionMessage>
                </i:EventTrigger>
            </MenuItem>
        </ContextMenu>
    </TextBox.ContextMenu>
</TextBox>
```

**Comment by jonferreira** [comment] 2015-05-08 08:41
Unfortunately i'll have to agree with you, the full syntax seems to be the best approach.
Disappointed though as i really hoped i would use the short syntax and still maintain MVVM pattern.
Thanks for your help!

**Comment by jonferreira** [comment] 2015-05-08 10:24
So it seems the full syntax won't work either, it creates a new sub-menu instead. weird!

**Comment by nigel-sampson** [comment] 2015-05-10 20:43
That's weird, I'll look into that.

**Comment by nigel-sampson** [comment] 2015-05-11 03:37
After some trial and error I have the following working.

``` xml
<TextBox x:Name="Entry">
    <TextBox.ContextMenu>
        <ContextMenu x:Name="ContextMenu">
            <MenuItem Header="Paste">
                <i:Interaction.Triggers>
                    <i:EventTrigger EventName="Click">
                        <cm:ActionMessage MethodName="Paste">
                            <cm:Parameter Value="{Binding RelativeSource={RelativeSource AncestorType=ContextMenu}, Path=PlacementTarget.Name, UpdateSourceTrigger=PropertyChanged}"/>
                            <cm:Parameter Value="{Binding RelativeSource={RelativeSource AncestorType=ContextMenu}, Path=PlacementTarget.CaretIndex, UpdateSourceTrigger=PropertyChanged}"/>
                        </cm:ActionMessage>
                    </i:EventTrigger>
                </i:Interaction.Triggers>
            </MenuItem>
        </ContextMenu>
    </TextBox.ContextMenu>
</TextBox>
```

``` csharp
public void Paste(string name, int caretIndex)
{
            
}
```

The problem is with as usual with context menus, how they work in the visual tree and what that does to bindings. I used http://stackoverflow.com/questions/2617122/wpf-menuitem-command-binding-to-elementname-results-to-system-windows-data-error as a reference.

**Comment by jonferreira** [comment] 2015-05-11 14:32
Hi Nigel,
Thanks for taking the time to look into this. Your suggestion seems to work quite nicely and the best one so far. Thanks for the help.
Now i'll just have to find out how to use that with ItemsSource and finish this! I was trying to use ItemContainerStyle but i don't think there's a Setter for EventTrigger.

```xaml
<TextBox x:Name="Entry">
    <TextBox.ContextMenu>
        <ContextMenu x:Name="ContextMenu"  ItemsSource="{Binding ContextMenu}">
         ....
        </ContextMenu>
    </TextBox.ContextMenu>
</TextBox>
```

**Comment by nigel-sampson** [comment] 2015-05-11 23:28
Glad I could help, closing this out since the problem was the WPF binding.

**Closed by nigel-sampson** 2015-05-11 23:28 UTC
