### ISSUE TITLE
Message.Attach has repeat multiple action 

### ISSUE THREAD

**Issue by EDiaos** [Caliburn-Micro/Caliburn.Micro#268] opened 2015-12-13 15:18 UTC
The project references the DLL version of V3.0.0, found an interesting bug,

>1.when I set up a SplitView-Frame-View NavigationCacheMode = Required
>2.The ListView-DataTemplate-Grid settings Tapped Action like this :[Event "Tapped] cm:Message.Attach= = [ShowDetail ()]"
>The ShowDetail action main job: NavigationService.For<DetailViewModel> (someVM).Navigate ();
>3.After the jump page to return, and then click Item, found that ShowDetail will happen twice ShowDetail action, and then return to the three.
>4.I found the other button attach action also happen this problem

>this is my code :  https://github.com/EDiaos/CaliburnMessageAttachBugTest
>you can found the problem in TimeLineViewModel.cs ShowDetail Action then you check listViewItem,and back ,and recheck,back

If you have time, please help me, thank you very much.

**Comment by mvermef** [comment] 2015-12-13 15:35
The only thing I see is you don't tell the navigationservice to use the new frame adapter when it is created.  reference the state sample in 3.0.0 branch

**Comment by EDiaos** [comment] 2015-12-13 16:08
This is my code : ViewModelBase.NavigationService = _container.RegisterNavigationService(frame, cacheViewModels: true);

My code is the same as helloUwp caliburn.micro on frame. You can down my code and try to run it .

**Comment by EDiaos** [comment] 2015-12-13 16:32
I found no problem at Alpha 3.0.0, working very well.

**Comment by nigel-sampson** [comment] 2015-12-13 19:30
Thanks for the report, I wonder if it's related to https://github.com/Microsoft/XamlBehaviors/issues/55 .

I would also test if removing the `NavigationCacheMode="Required"` resolves the issue.

**Comment by nigel-sampson** [comment] 2015-12-13 21:33
Just saw the description of the other repository. Given that it's resolved by removing `NavigationCacheMode="Required"` I can almost guarantee it's being caused by Microsoft/XamlBehaviors#55 .

You can test this by building `Microsoft.Xaml.Behaviors.Uwp.Managed` from source and using that.

**Comment by EDiaos** [comment] 2015-12-14 09:50
Nice,using the new  Microsoft.Xaml.Behaviors.Uwp.Managed source fix it, work well . TKS!

**Comment by nigel-sampson** [comment] 2015-12-14 10:55
Glad it's resolved.

**Closed by nigel-sampson** 2015-12-14 10:55 UTC
Labels: more info required
