### ISSUE TITLE
Issues to bind HeaderedContentControl ?

### ISSUE THREAD

**Issue by oschwab** [Caliburn-Micro/Caliburn.Micro#451] opened 2017-06-13 13:09 UTC
Hi,

I'm evaluating CM jointly to  Mahapps toolkit.
I face the following issue : https://github.com/MahApps/MahApps.Metro/issues/2953
Basically, since Mahapps changed its flyout control to inherit from HeaderedContentControl (instead of ContentControl) , CM seems unable to locate viewmodels for flyout views.

I found no correct workaround for this , but I'm far from being a CM expert.
Anyone has an idea how to solve (or correctly workaround) this ?

**Comment by nigel-sampson** [comment] 2017-06-13 21:00
I'm happy to take a look at it if you can create a sample repository illustrating the problem

**Comment by oschwab** [comment] 2017-06-14 07:45
If you get Mahapps repo, you have samples that involve CM.
![image](https://user-images.githubusercontent.com/2461647/27121039-0ed6cc88-50e6-11e7-91eb-de507e26ecde.png)

Neither 4.0 or 4.5 sample executes correctly on my side.

If you need something less heavy I could make a quick sample that demonstrates the issue.

**Comment by nigel-sampson** [comment] 2017-06-15 11:34
There's something really weird going on here and I'm still tracking down the cause. 

From what I can it's almost like the `ItemTemplate` of the `FlyoutsControl` is being applied to the `HeaderTemplate` of the `Flyout` and vice versa.

**Comment by nigel-sampson** [comment] 2017-06-15 11:59
So the sample is using the `ItemsControl` convention on top of the `FlyoutsControl`, this sets up the `ItemSource` binding to `FlyoutViewModels` and sets the `ItemTemplate` to the default template for Caliburn.

Somehow however this is heading up in the `HeaderTemplate` of the `Flyout` causing it try and resolve the header and the crash, and because the `ItemTemplate` isn't set then we get don't show the view.

**Comment by nigel-sampson** [comment] 2017-06-15 12:06
Updating the sample to the following works, it does this because we've replace the `x:Name` with the binding so we don't have conventions applied. We've also set the `ContentTemplate` property on the `Flyout` in order to find our view correctly.

This is a definite workaround, I've yet to work out why setting the `ItemTemplate` on the `FlyoutsControl` ends up as the `HeaderTemplate` of the `Flyout`. My gut says this part isn't related to Caliburn.Micro, but I need to spike a sample to test that out.

``` xml
<Controls:MetroWindow.Resources>
    <Style x:Key="CustomFlyoutStyle"
           BasedOn="{StaticResource {x:Type Controls:Flyout}}"
           TargetType="{x:Type Controls:Flyout}">
        <Setter Property="Header" Value="{Binding Header}" />
        <Setter Property="ContentTemplate">
            <Setter.Value>
                <DataTemplate>
                    <ContentControl cal:View.Model="{Binding}" />
                </DataTemplate>
            </Setter.Value>
        </Setter>
        <Setter Property="IsOpen" Value="{Binding IsOpen}" />
        <Setter Property="Position" Value="{Binding Position}" />
        <Setter Property="Theme" Value="{Binding Theme}" />
    </Style>
</Controls:MetroWindow.Resources>

<Controls:MetroWindow.Flyouts>
    <Controls:FlyoutsControl ItemsSource="{Binding FlyoutViewModels}" ItemContainerStyle="{StaticResource CustomFlyoutStyle}">
    </Controls:FlyoutsControl>
</Controls:MetroWindow.Flyouts>
```

**Comment by oschwab** [comment] 2017-06-15 12:13
I've read somewhere that CM samples in Mahapps.Metro are not real good examples of CM usage.
This workaround works in my application too , so that's OK for me.
Thanks for your fast intervention .

**Comment by jamithiran** [comment] 2017-06-15 17:07
Thanks again, appreciate your support.

**Comment by nigel-sampson** [comment] 2017-06-15 23:43
I've managed to recreate the bug sans Caliburn.Micro with some code posted in MahApps/MahApps.Metro#2953 so will close this one out.

**Closed by nigel-sampson** 2017-06-15 23:43 UTC
Labels: bug, more info required
