### ISSUE TITLE
Slow Response viewing CM screens

### ISSUE THREAD

**Issue by BobRanck** [Caliburn-Micro/Caliburn.Micro#382] opened 2016-10-21 01:31 UTC
I use CM Ver. 1.5.2.0 in a WPF application using the Hello Screens design pattern.

Unlike the Sample project my real application has a lot of controls on each of the Screens like Customers, Orders, etc. ,  bottom line is that after a click of the icon at the bottom of the Shell "Home" screen it takes **3 to 6 seconds** for some screens to become visible the first time. (usually less if clicked a second time).  This appears to the user as an application that has poor performance, so I implemented a busy indicator to show that something was happening and also to free up the UI.

In the DocumentWorkspace (again from the CM Sample Screens project) I modified the sample code to show a BusyIndicator - then the next line of code is Conductor.Activate(this).  Of course the result is that user does not see the BusyIndicator control until after the screen is displayed.  Not good.

The natural place to turn was Frameworks new Async and Await key words.  I created a sample project with a 4 Second Task.Delay and viola - - - The BusyIndicator works fine and closes after the screen is displayed. 
Code (in DocumentWorkspace) now
[CaliburnMicro.AsyncDemo-master.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/543304/CaliburnMicro.AsyncDemo-master.zip)
 reads 
1.)  ShowBusy
2.)  Await Task.Delay(4000)
3.)  Condutor.Activate(this)
4.)  CloseBusy

Cool , so all I have to do is move conductor.activate(this) to a new thread (task) and the jobs done.  But wait, that doesn’t work either because conductor.activate(this) **really can’t be moved to another thread**.  

I have been trying to get some advice on StackOverflow but with no luck.  I have a sample project also based on the "Hello Screens" sample, that demonstrates the problem, and would be happy to provide it to whoever would take a look at it.

Bob Ranck

**Comment by BobRanck** [comment] 2016-10-31 03:42
You may have had difficulty following my demo, if you currently work in the latest release of Caliburn Micro

## I have made several changes to the demo project to make it easier.

1.) The Demo has been upgraded to the latest CM release Ver 3.0.1
	(upgrading is not easy and for the benefit of others I have
	 made a list [at the bottom of this note] of necessary
	changes)
2.) On the Orders Workspace, I added code behind that adds a stack
	of 1000 textboxes. Depending on the speed of your machine
	this will take about 3 to 4 sec to load the OrdersWorkspaceView.
	This is just for Demo so Code Behind was a quick way to do it.

In the Framework Namespace the Show method is changed to ShowAsync, like this:

        Public Async Sub ShowAsync() Implements HelloScreensWPF.Framework.IWorkspace.ShowAsync
            'Notice that this Sub is Async and the Name is changed from Show (In the CM Sample) to Show Async
            'Not sure this is the very best way but it works pretty good
            'Anytime the user clicks an icon at the bottom of the UI this sub is called
            Dim haveActive = TryCast(Parent, IHaveActiveItem)
            If haveActive IsNot Nothing AndAlso haveActive.ActiveItem Is Me Then
                DisplayName = IconName
                State = DocumentWorkspaceState.Master
            Else
                'We need to have access to the ShellViewModel
                Dim Svm = CType(Parent, ShellViewModel)


                'The BusyIndicatorViewModel has a built in '200 µ Sec Delay
                'So if it is Deactivated before it 'fires' the user will not see a
                'flash of an unnecessary Busy Indicator

                'Activate the Busy indicator
                Svm.ShellBusyIndicator.ShowBusyIndicator(True, True, "Loading", IconName)

                Await Task.Run(Sub() Conductor.ActivateItem(Me))

                Dim List = CType(Parent, IConductor).GetChildren

                'Deactivate Busy Indicator
                Svm.ShellBusyIndicator.ShowBusyIndicator(False)

            End If
        End Sub

### Even though the ActivateItem(me) is 'Awaited'. when you click the Orders Icon you will see nothing for 3 to 4 Seconds, then a brief flash of the Busy Indicator and finally the Orders Screen.

Of course the desired effect would be to view the BusyIndicator while the Orders are being found in the database and the **OrdersWorkspaceView is being prepared**, then exposing the view and finally hiding the Busy Indicator.     Could this somehow be accommodated in Caliburn?  Is this a case where placing a control on a different thread rather than the UI would be the answer? If so how would this be done?

After the Orders Workspace is available, you see essentially the same issue when you click the
 "New" Order Button, but with the delay in this case is simulated with a Task.Await.

The Customers Detail Screen has a tester that shows how the BusyIndicator works with Text and Progress Reports.

**It would be nice to hear from someone with an approach to solve the problems of Showing a Busy control for Slow Workspace loads and (if different) how to do it for Slow Order or Customer Detail loads.**

BTW - I work in VB, if you must have the code in C#, I use http://converter.telerik.com/ (you can convert the project as a batch to C#)
BTW2 - The Hello Screens Solution views are in color just for the purpose of understanding the relationship of the various parts.

## Here is the New HelloScreensWPF Solution
[HelloScreensWPF - VB -wBusy.zip](https://github.com/Caliburn-Micro/Caliburn.Micro/files/561034/HelloScreensWPF.-.VB.-wBusy.zip)

# Info for Upgraders
(not really part of the Slow/Busy Indicator Issue)
First if you are upgrading from 1.3.0 you will need to change this line in HelloScreensFramework.DocumentWorkspace (adding the argument for 'Class').

    'Public MustInherit Class DocumentWorkspace(Of TDocument As {INotifyPropertyChanged, IDeactivate, IHaveDisplayName}) Old Version CM 1.3.0
    Public MustInherit Class DocumentWorkspace(Of TDocument As {Class, INotifyPropertyChanged, IDeactivate, IHaveDisplayName}) 

### Upgrading HelloScreensWPF to CM 3.0.1

1.) In References you will need
	Caliburn.Micro	3.0.1.0
	Caliburn.Micro.Platform	3.0.1.0
	Caliburn.Micro.Platform.Core 3.0.1.0  (not sure about the nee for this but I added it)

2.)In ScreenBootstrapper make the changes below

	'Inherits Bootstrapper(Of IShell)       Old Prior to Version 3.0.1.0 
        Inherits BootstrapperBase
        Private container As CompositionContainer
		Private mainWindow As Window
        Private actuallyClosing As Boolean

        Public Sub New()                        'Added For New Version 3.0.1.0 
            Initialize()
        End Sub

        Protected Overrides Sub OnStartup(sender As Object, e As StartupEventArgs)      'Added For New Version  
            DisplayRootViewFor(Of IShell)()
        End Sub

        'Protected Overrides Sub OnStartup(ByVal sender As Object, ByVal e As StartupEventArgs)     'Old Prior to Version 3.0.1.0
        '	MyBase.OnStartup(sender, e)
        '		mainWindow = Application.MainWindow
        '		AddHandler mainWindow.Closing, AddressOf MainWindowClosing

        'End Sub

3. In Every View you will need to change the CAL name space reference to:
	xmlns:cal="clr-namespace:Caliburn.Micro;assembly=Caliburn.Micro.Platform"

4. In the ApplicationCloseStrategy  Evaluate method change the execute line as follows:
	                    'sequential.Execute(New ActionExecutionContext()) Old Prior to Version 3.0.1.0
                    sequential.Execute(New CoroutineExecutionContext())

Sounds like 4 easy steps but takes a lot of time to dig out these pieces, you will want to go back and read the documentation to understand these changes.

**Comment by nigel-sampson** [comment] 2016-10-31 08:11
Apologies, I've been living out of a suit case with no internet at home for the couple of weeks, did you mean to close this issue?

It does sounds like there's extra work being done on the UI thread than should be, I'll dig into the samples as I can.

**Comment by BobRanck** [comment] 2016-10-31 11:47
Oh, my goodness No.  I was so tired last night that I must have hit the wrong button.

 

Let me know if you need more info or anything I can do to help.

 

Nigel, Since the Hello Screens sample is in Silverlight, my Sample could also help those who need to understand CM in MEF when working in WPF.

 

Bob Ranck

**Comment by nigel-sampson** [comment] 2016-11-01 10:05
Most of what's in the sample here just complicates finding the problem. Ideally a repo shows the problem in it's most simplistic form.

The main cause of the slow load here is creation of 1000 text boxes in the constructor of `OrdersWorkspaceView`. It's this constructor which slows the operation down and no amount of async can change this since the creation of the view must happen on the UI thread.

I would look into solutions that mean the full size of this UI isn't created all at once. If you really do have something like 1000+ text boxes in the real app then using item virtualization so only the UI required on screen is actually created.

**Closed by nigel-sampson** 2016-11-01 10:05 UTC

**Comment by BobRanck** [comment] 2016-11-01 15:54
Hi Nigel,

 

Before I continue, a few personal notes:

 

Thank you for taking the time to look at my issue.  My appreciation is even more profound when I realize that your life has recently been “on the move” as well.

 

Here in the USA Nigel is not a name that one would frequently encounter.  So I looked it up, and found some interesting facts – It’s a name of a person most frequently from England or Wales . . .  could possibly have Norman origins . . . but may not be a complementary name if one is from Australia . . . while in England there is long string of very successful people with the name of Nigel.  Interestingly, the odds are high that you were born somewhere between 1950 and 1970, as there was a peak in the usage of that name during this period.

 

As you may know, we have a very contentious election coming up in the USA, and a commentator looking at the “political wreckage” in the news made the observation that Winston Churchill once said, “Don’t worry, the Americans will get it right . . . after they have exhausted every other possibility”.

 

Unfortunately, the portent of his words seem to have settled in on my software development.

 

 

My actual CM solution has 28 projects including both a custom 2D and 3D CAD system implemented in WPF and using CM too (all modeled on the Hello Screens design pattern) so “simplistic sample” might be considered a relative term.  In short, my Visual Studio application solution is immense.

 

I would love to take a few screen shots to show you an example of caliburn micro used to the extreme but considering how busy you are, would not do so unless you asked.

 

 

Back to business,

 

I apologize for an overly complex repro. 

 

Do you think that many other people have used the Hello Screens (Billy Hollis) pattern of application design?  At some level, others must run into the same slow to load issue.  The problem is that Hello Screens offers a clever and innovative pattern of application design, Robs original explanation of its design was excellent, but of course you are kind of on your own when it comes to extending.  While I am very good at implementing CAD in WPF, I’m not nearly as good as you or Rob in understanding the inner workings of CM.

 

The real app does not have 1000 controls on any screen but still experiences a significant delay in rendering.  For example in the real app, one small popup screen has just 20 controls but still takes almost 2 Seconds to be viewed, (It does use a lot of WPF features for relative spacing and control templates to determine the appearance of the controls.)  I have done all kinds of timing analysis to try to find a way around the problem but so far without results.  I will continue my research but in the meantime I need to show that something is going on after a click.  In some cases perhaps just a screen overlay that says “Loading…” or in other more complex cases display a control like BizzySpinner on a screen overlay, that would report progress and offer an opportunity to abort.

 

I have long felt that the answer may be to (God forbid) let another thread control a simple, otherwise transparent, screen overlay with a text block that says Loading…(or the BusyIndicator Control for really long activities).  But the problem is I  don’t  have the slightest idea  how to do that in the Hello Screens pattern.   I have lots of experiments where I can show an overlay from another thread is static situations, but just can’t do it in CM.  So my reasoning was that the large repro was really needed to actually see the problem and offer a platform for solution in the form of the Hello Screens sample that already exists on the CM site.

 

I tried not to suggest the answer I was looking for because, I was not sure that I was not stuck down in some rat hole and that a better and simpler solution would materialize from a real expert.

 

Bob Ranck

**Comment by nigel-sampson** [comment] 2016-11-02 09:46
From what I can see in the sample, ALL the delay is being caused by the constructor of the view. I can create the problem completely outside of Caliburn.Micro. Simply creating a complex user control and adding to a content control can lock up the UI thread.

I would start bisecting the interfaces being delayed to track down the offending components.

**Comment by BobRanck** [comment] 2016-11-02 13:27
Nigel,

 

My conclusion is that the answer is to show a  Loading… indicator on another thread. I already know how to do that. 

 

I guess I did not make myself clear.  I understand how to track down offending components.  At this point it’s not a question of how to make loading faster.   My application involves CAD and often a Pop-up needs to draw a new CAD image from data. (Think of clicking on a map of England and having a small popup containing a map inset of Coventry  pop-up which also had a text box to enter search criteria for an address and then re-focus the pop-up image on a specific street address.  This not what I do but illustrates the complexity . . .  as my previous use of 1000 text boxes also was meant to do).  So my last email said….

 

I have long felt that the answer for Slow loading may be to (God forbid) let another thread control a simple, otherwise transparent, screen overlay with a text block that says Loading…(or the BusyIndicator Control for really long activities).  But the problem is I  don’t  have the slightest idea  how to do that in the Hello Screens pattern.   I have lots of experiments where I can show an overlay from another thread is static situations, but just can’t do it in CM.  So my reasoning was that the large repro was really needed to actually see the problem and offer a platform for solution in the form of the Hello Screens sample that already exists on the CM site.

 

 

Boy, this is so close to a discussion you are having on another issue about Async/Await related to Screens (Issue 245).

 

To be more specific, What I don’t know is what to grab (and how to get at it)  in CM that would initiate the indicator (which would be displayed on another thread) when a CM screen is activated . . .  and what and how to grab something in CM that can be used to stop the indicator on the other thread when the CM Screen has completed loading. 

 

Bob Ranck

**Comment by nigel-sampson** [comment] 2016-11-03 08:31
Ok, so the "Hello.Screens" pattern is simply just composition of view models, meaning it doesn't add extra complication to this. Just need to think about it in terms of the MVVM pattern.

In this example it's the responsibility of the main conductor to handle the movement between the child view models. One possible approach is null out the `ActiveItem` before switching to the new one. This would "blank" the screen until the new content is loaded. Binding something in the conductors view to show when the Active is null to show progress would solve this without needing services or anything complicated.
